let is_sidebar_open = false;

// Get the radio data of the country
function getData(country) {
  // dark the content other than sidebar and disable mouse events on it

  document.getElementById("stations").innerHTML = "";
  document.getElementById("countryName").innerText = country;
  document.getElementById("country_info").style.display = "flex";

  // Loading animation
  document.getElementById("stations").innerHTML = `<div class="station">
    <svg id="loading" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: #11101d; display: block; shape-rendering: auto;" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="84" cy="50" r="10" fill="#85a2b6">
    <animate attributeName="r" repeatCount="indefinite" dur="0.25s" calcMode="spline" keyTimes="0;1" values="10;0" keySplines="0 0.5 0.5 1" begin="0s"></animate>
    <animate attributeName="fill" repeatCount="indefinite" dur="1s" calcMode="discrete" keyTimes="0;0.25;0.5;0.75;1" values="#85a2b6;#fdfdfd;#dce4eb;#bbcedd;#85a2b6" begin="0s"></animate>
</circle><circle cx="16" cy="50" r="10" fill="#85a2b6">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"></animate>
</circle><circle cx="50" cy="50" r="10" fill="#bbcedd">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.25s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.25s"></animate>
</circle><circle cx="84" cy="50" r="10" fill="#dce4eb">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"></animate>
</circle><circle cx="16" cy="50" r="10" fill="#fdfdfd">
  <animate attributeName="r" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.75s"></animate>
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.75s"></animate>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg>
            </div>`;

  fetch(`http://de1.api.radio-browser.info/json/stations/bycountry/${country}`)
    .then((response) => response.json())
    .then((data) => {
      
      is_sidebar_open = true;
      document.getElementById("content").style.filter = "brightness(0.4)";
      document.getElementById("stations").innerHTML = "";
      document.getElementById("content").style.pointerEvents = "none";
      if (data.length === 0) {
        document.getElementById("stations").innerHTML = `<div class="station">
                No stations found
                </div>`;
      } else {
        data.forEach((station) => {
          console.log(station.name);
          const div = document.createElement("div");
          div.setAttribute("class", "station");
          if (station.favicon === "") {
            station.favicon = `https://static-00.iconduck.com/assets.00/radio-icon-512x512-1fsdmutz.png`;
          }
          div.innerHTML = `
                    <img src=${station.favicon} alt="flag">
                    <h3>${station.name}</h3>
                `;
          document.getElementById("stations").appendChild(div);
        });
      }
    }).catch((error) => {
      console.error('Error:', error);
      document.getElementById("stations").innerHTML = `<div class="station">
                Error fetching stations
                </div>`;
    });
}

// On click outside the sidebar, close the sidebar
document.getElementById("main").addEventListener("click", function () {
  console.log(is_sidebar_open);
  if (is_sidebar_open) {
    document.getElementById("country_info").style.display = "none";
    document.getElementById("content").style.filter = "brightness(1)";
    document.getElementById("content").style.pointerEvents = "auto";
    is_sidebar_open = false;
  }
});

document.getElementById("sidebar_close").addEventListener("click", function () {
  document.getElementById("country_info").style.display = "none";
  document.getElementById("content").style.filter = "brightness(1)";
  document.getElementById("content").style.pointerEvents = "auto";
  is_sidebar_open = false;
});

// On Hover on the country, show the country name
document.querySelectorAll(".allPaths").forEach((e) => {
  e.setAttribute("class", `allPaths ${e.id}`);
  document.getElementById("name").style.zIndex = 1000;
  e.addEventListener("mouseover", function () {
    window.onmousemove = function (j) {
      x = j.clientX;
      y = j.clientY;
      document.getElementById("name").style.top = y - 60 + "px";
      document.getElementById("name").style.left = x + 10 + "px";
    };
    const classes = e.className.baseVal.replace(/ /g, ".");
    document.querySelectorAll(`.${classes}`).forEach((country) => {
      country.style.fill = "red";
    });
    document.getElementById("name").style.opacity = 1;

    document.getElementById("name").innerText = e.id;
  });
  e.addEventListener("mouseleave", function () {
    const classes = e.className.baseVal.replace(/ /g, ".");
    document.querySelectorAll(`.${classes}`).forEach((country) => {
      country.style.fill = "#ececec";
    });
    document.getElementById("name").style.opacity = 0;
  });

  e.addEventListener("click", function () {
    getData(e.id);
  });
});
